FROM ruby:3.0.0 
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y build-essential nodejs yarn\
  && apt-get install -y nodejs mariadb-client
RUN mkdir /AccountingApp
WORKDIR /AccountingApp
COPY Gemfile /AccountingApp/Gemfile
COPY Gemfile.lock /AccountingApp/Gemfile.lock
RUN bundle install
COPY . /AccountingApp

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3001

CMD ["rails", "server", "-b", "0.0.0.0"]